# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - run: yarn build

      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"

      - run:
          name: "Sending build directory into a host"
          command: scp -P 88 -r ./build/* ${HOST_USER}@${HOST_ADDRESS}:~/app/client

      - run:
          name: "Restaring nginx"
          command: ssh -p 88 ${HOST_USER}@${HOST_ADDRESS} sudo systemctl restart nginx